---
- name: GitHub self-hosted runner builder
  hosts: all
  vars:
    - gh_runner_config_token: ''
    - gh_runner_env_label: ''
    
  pre_tasks:
    - name: Update_cache
      become: true
      ansible.builtin.apt:
        update_cache: yes
        
  roles:

    - role: geerlingguy.pip
      become: true

    - role: geerlingguy.nodejs
      become: true

    - role: geerlingguy.ansible
      become: true
    
    - role: geerlingguy.docker
      become: true
      vars:
        docker_users:
          - ubuntu

    - role: macunha1.github_actions_runner
      vars:
        gh_runner_config_name: AWS-self-hosted-runner-{{ gh_runner_env_label }}
        gh_runner_config_url: https://github.com/red-devops
        gh_runner_config_token: "{{ gh_runner_config_token }}"
        gh_runner_version: 2.302.1
        gh_runner_config_labels:
          - self-hosted
          - "{{ gh_runner_env_label }}"

  tasks:
    - name: Install extra lib
      become: true
      apt:
        name: "{{ item }}"
      loop: 
        - jq
        - zip

    - name: Install AWS CLI 
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        
    - name: Install python lib
      shell: |
        pip3 install boto3 botocore
    
    - name: HashiCorp Tools
      become: true
      unarchive:
        src: "{{ item }}"
        dest: "/usr/local/bin"
        remote_src: yes
        owner: "root"
        group: "root"
      with_items:
        - "https://releases.hashicorp.com/packer/1.9.2/packer_1.9.2_linux_amd64.zip"
        - "https://releases.hashicorp.com/terraform/1.5.4/terraform_1.5.4_linux_amd64.zip"
        - "https://releases.hashicorp.com/vault/1.14.1/vault_1.14.1_linux_amd64.zip"
        - "https://releases.hashicorp.com/consul/1.16.0/consul_1.16.0_linux_amd64.zip"
        - "https://releases.hashicorp.com/nomad/1.6.0/nomad_1.6.0_linux_amd64.zip"
        - "https://releases.hashicorp.com/nomad-pack/0.1.0/nomad-pack_0.1.0_linux_amd64.zip"
      
  
