---
name: Continuous Integration

"on": # Ref: https://github.com/adrienverge/yamllint/issues/430#issuecomment-1107440224
  push:
    branches: ["**"]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Enable cache for (pip) dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Lint | Check Ansible and YAML
        run: |
          python -m pip install --upgrade pip
          python -m pip install yamllint ansible ansible-lint

          yamllint -c .github/actions/config/yamllint.yaml .
          ansible-lint -c .github/actions/config/ansible.yaml .

      - name: Galaxy | Import
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          ansible-galaxy role import \
            --api-key ${ANSIBLE_GALAXY_API_KEY} \
            --branch master \
            macunha1 github_actions_runner
        env:
          ANSIBLE_GALAXY_API_KEY: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
